name: 'Azure Pipelines QMK'
trigger: [ 'master' ]
pool:
  name: 'Hosted Ubuntu 1604'
steps:
- bash: |
    sudo sh -c 'printf "APT::Get::Assume-Yes \"true\";\nAPT::Get::force-yes \"true\";" > /etc/apt/apt.conf.d/01qmk-build'
    sudo util/linux_install.sh
    make tkc1800:default
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '.build'